/**
 * Exact web copy for the Journal section (messages/en.json → `journal.*`,
 * plus the two `plan.*` strings PhotoGallery uses). Keep verbatim — string
 * parity with the web app is a spec requirement.
 */
export const STR = {
  loading: 'Loading your journal…',
  errorHeadline: "Couldn't load your journal",
  errorSubtext: 'Check your connection and try again.',
  entries: 'Entries',
  readingList: 'Reading list',
  photography: 'Photography',
  newEntry: 'New entry',
  emptyHeadline: 'No journal entries yet',
  emptySubtext: 'Write about your day, add a few photos.',
  back: 'Back',
  edit: 'Edit',
  editEntry: 'Edit entry',
  titleLabel: 'Title',
  dateLabel: 'Date',
  bodyLabel: 'Entry',
  save: 'Save',
  cancel: 'Cancel',
  deleteEntry: 'Delete entry',
  confirmDelete: 'Tap again to delete',
  titleRequired: 'Add a title for this entry.',
  saveFailed: "Couldn't save. Try again.",
  mutationFailed: 'Something went wrong. Try again.',
  offlineHint: "You're offline — editing is paused until you reconnect.",
  mdToolbar: 'Formatting',
  mdBold: 'Bold',
  mdItalic: 'Italic',
  mdHeading: 'Heading',
  mdList: 'List',
  mdLink: 'Link',
  addPhoto: 'Add a photo',
  addPhotoOffline: 'Reconnect to add photos.',
  uploadingPhoto: 'Uploading…',
  photosAfterSaveHint: 'Save the entry first, then add photos.',
  photoNotImage: "That file isn't an image.",
  photoTooLarge: 'That image is too large (max 10 MB).',
  photoTooMany: "You've reached the photo limit for this entry.",
  photoUploadFailed: "Couldn't upload that photo. Try again.",
  addLink: 'Add link',
  editLink: 'Edit link',
  urlLabel: 'URL',
  noteLabel: 'Note',
  previewFetching: 'Fetching preview…',
  previewFailed: "Couldn't fetch a preview — add the details yourself.",
  linksEmptyHeadline: 'No saved links yet',
  linksEmptySubtext: 'Save blogs and articles to read before your trip.',
  invalidUrl: 'Enter a valid http(s) link.',
  /** Link rows/sheet use a plain "Delete" (spec) — single-tap, no confirm. */
  deleteLink: 'Delete',
  photoListsEmptyHeadline: 'No photo lists yet',
  photoListsEmptySubtext: 'Make a list and collect shots you want to take when you get there.',
  newPhotoList: 'New list',
  createList: 'Create',
  renameList: 'Rename list',
  listNamePlaceholder: 'List name (e.g. Sunset spots)',
  listNameLabel: 'List name',
  listNameRequired: 'Name this list.',
  deleteList: 'Delete list',
  confirmDeleteList: 'Tap again to delete this list and its photos',
  addPhotos: 'Add photos',
  photoListEmpty: 'No photos yet — add reference shots below.',
  // PhotoGallery (web `plan.*`)
  photosLabel: 'Photos',
  closePhoto: 'Close photo',
} as const;

/** "No photos" / "1 photo" / "{n} photos" (web `journal.photoCount` plural). */
export function photoCountLabel(n: number): string {
  return n === 0 ? 'No photos' : n === 1 ? '1 photo' : `${n} photos`;
}
